name: Build ETFinix EXE

on:
  workflow_dispatch: # এটি আপনাকে ম্যানুয়ালি রান করার সুযোগ দেবে

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive # mtkclient এর জন্য প্রয়োজন হতে পারে

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --name ETFinix ETFinix.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ETFinix-Tool-Windows
        path: dist/ETFinix.exe
